{
  "kind": "PipelineRun",
  "apiVersion": "tekton.dev/v1beta1",
  "metadata": {
    "generateName": "simple-two-step-pipeline-gongyuan-1609817103-",
    "creationTimestamp": null
  },
  "spec": {
    "pipelineSpec": {
      "tasks": [
        {
          "name": "producer",
          "taskRef": {
            "name": "kfp-executor"
          },
          "params": [
            {
              "name": "kfp-task-spec",
              "value": "{\"taskInfo\":{\"name\":\"Producer\"},\"inputs\":{\"parameters\":{\"text\":{\"componentInputParameter\":\"text\"}}},\"outputs\":{\"parameters\":{\"output_value\":{\"type\":\"STRING\"}}},\"executorLabel\":\"Producer\"}"
            },
            {
              "name": "kfp-context-name",
              "value": "{{inputs.parameters.kfp-context-name}}"
            },
            {
              "name": "kfp-executor-spec",
              "value": "{\"container\":{\"image\":\"google/cloud-sdk:latest\",\"command\":[\"sh\",\"-c\",\"set -e -x\\necho \\\"$0, this is an output parameter\\\" | gsutil cp - \\\"$1\\\"\\n\",\"{{$.inputs.parameters['text']}}\",\"{{$.outputs.parameters['output_value'].output_file}}\"]}}"
            },
            {
              "name": "kfp-outputs-spec",
              "value": "{\"parameters\":{\"output_value\":{\"type\":\"STRING\"}}}"
            }
          ]
        },
        {
          "name": "consumer",
          "taskRef": {
            "name": "kfp-executor"
          },
          "runAfter": [
            "producer"
          ],
          "params": [
            {
              "name": "kfp-task-spec",
              "value": "{\"taskInfo\":{\"name\":\"Consumer\"},\"inputs\":{\"parameters\":{\"input_value\":{\"taskOutputParameter\":{\"producerTask\":\"Producer\",\"outputParameterKey\":\"output_value\"}}}},\"executorLabel\":\"Consumer\"}"
            },
            {
              "name": "kfp-context-name",
              "value": "{{inputs.parameters.kfp-context-name}}"
            },
            {
              "name": "kfp-executor-spec",
              "value": "{\"container\":{\"image\":\"google/cloud-sdk:latest\",\"command\":[\"sh\",\"-c\",\"set -e -x\\necho \\\"Read from an input parameter: \\\" \\u0026\\u0026 echo \\\"$0\\\"\\n\",\"{{$.inputs.parameters['input_value']}}\"]}}"
            },
            {
              "name": "kfp-outputs-spec",
              "value": "{}"
            }
          ]
        }
      ],
      "params": [
        {
          "name": "kfp-context-name"
        }
      ]
    },
    "params": [
      {
        "name": "task-spec",
        "value": "{\"taskInfo\":{\"name\":\"hello-world-dag\"},\"inputs\":{\"parameters\":{\"text\":{\"runtimeValue\":{\"constantValue\":{\"stringValue\":\"Hello, World!\"}}}}}}"
      }
    ]
  },
  "status": {}
}
